spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/jobSeeker?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: postgres
    password: WaPpys6c4nGJGR6n
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 9ee963d0defd6eec1e30ca5392602131823156db5828db93cf294e151173f0f1200e41d66d006e60d9bc051b5cc8b04211e802669e1097cd92f5eef723861587
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days